name: Tekton Dashboard Nightly Build

on:
  push:
    branches:
      - nightly-with-plumbing-action
  schedule:
    # Run at 03:00 UTC daily #test1
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      kubernetes_version:
        description: 'Kubernetes version to test with'
        required: false
        default: 'v1.33.x'
      nightly_bucket:
        description: 'Nightly bucket for builds'
        required: false
        default: 'gs://tekton-releases-nightly/dashboard'
        type: string

env:
  KUBERNETES_VERSION: ${{ inputs.kubernetes_version || 'v1.33.x' }}
  REGISTRY: ghcr.io
  PACKAGE: github.com/${{ github.repository }}
  BUCKET: ${{ inputs.nightly_bucket || 'gs://tekton-releases-nightly/dashboard' }}
  IMAGE_REGISTRY_PATH: ${{ github.repository }}
  IMAGE_REGISTRY_USER: tekton-robot

jobs:
  build:
    name: Nightly Build (K8s ${{ inputs.kubernetes_version || 'v1.33.x' }})
    runs-on: ubuntu-latest
    ## if: github.repository_owner == 'tektoncd'  # do not run this elsewhere

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate version info
        id: version
        run: |
          latest_sha=${{ github.sha }}
          date_tag=$(date +v%Y%m%d-${latest_sha:0:7})
          echo "version_tag=${date_tag}" >> "$GITHUB_OUTPUT"
          echo "latest_sha=${latest_sha}" >> "$GITHUB_OUTPUT"

      - name: Setup Tekton Nightly Infra
        uses: anithapriyanatarajan/plumbing/.github/actions/setup-nightly-infra@nightly-with-gha
        with:
          kubernetes_version: v1.33.x
          image_registry_user: tekton-robot
          ghcr_token: ${{ secrets.GHCR_TOKEN }}
          gcs_service_account_key: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}